import { db } from "@/db";
import { services } from "@/db/schema";
import { asc, eq } from "drizzle-orm";

const catalog = [
  { slug: "photo-editing", category: "creative", icon: "image", titleEn: "Photo Editing", titleUr: "فوٹو ایڈیٹنگ", shortEn: "Clean retouching, background work, and polished visual edits.", shortUr: "صاف ری ٹچنگ، بیک گراؤنڈ ورک اور معیاری تصویری تدوین۔", descriptionEn: "Professional editing tailored to your brief—from color correction and product cleanup to composites and social media assets. Scope and source files are reviewed before a genuine quote is issued.", descriptionUr: "آپ کی ہدایات کے مطابق پیشہ ورانہ ایڈیٹنگ—رنگوں کی درستگی، پروڈکٹ کلین اپ، کمپوزٹنگ اور سوشل میڈیا ڈیزائن۔ درست قیمت سے پہلے کام اور فائلوں کا جائزہ لیا جاتا ہے۔", deliveryEn: "Based on scope", deliveryUr: "کام کی نوعیت کے مطابق", fulfillmentType: "digital", featured: true },
  { slug: "video-editing", category: "creative", icon: "video", titleEn: "Video Editing", titleUr: "ویڈیو ایڈیٹنگ", shortEn: "Purposeful cuts, color, audio, captions, and motion graphics.", shortUr: "بامقصد کٹس، رنگ، آڈیو، کیپشن اور موشن گرافکس۔", descriptionEn: "Editing for short-form, YouTube, business, and personal content. Every project is scoped by footage length, output format, graphics, and turnaround before pricing.", descriptionUr: "شارٹ فارم، یوٹیوب، کاروباری اور ذاتی مواد کی ایڈیٹنگ۔ قیمت سے پہلے فوٹیج، آؤٹ پٹ فارمیٹ، گرافکس اور وقت کا تعین کیا جاتا ہے۔", deliveryEn: "Based on footage", deliveryUr: "فوٹیج کے مطابق", fulfillmentType: "digital", featured: true },
  { slug: "website-development", category: "development", icon: "code", titleEn: "Website Development", titleUr: "ویب سائٹ ڈیولپمنٹ", shortEn: "Fast, responsive websites built around real business goals.", shortUr: "حقیقی کاروباری مقاصد کے لیے تیز اور ریسپانسیو ویب سائٹس۔", descriptionEn: "Custom business sites, portfolios, landing pages, and web platforms. You receive a documented scope, milestone plan, and quote after discovery—never a made-up package price.", descriptionUr: "کسٹم بزنس سائٹس، پورٹ فولیو، لینڈنگ پیجز اور ویب پلیٹ فارمز۔ ابتدائی مشاورت کے بعد واضح دائرۂ کار، مراحل اور حقیقی قیمت فراہم کی جاتی ہے۔", deliveryEn: "Milestone based", deliveryUr: "مراحل کے مطابق", fulfillmentType: "digital", featured: true },
  { slug: "app-development", category: "development", icon: "smartphone", titleEn: "App Development", titleUr: "ایپ ڈیولپمنٹ", shortEn: "Practical mobile and web apps, planned from prototype to launch.", shortUr: "پروٹوٹائپ سے لانچ تک عملی موبائل اور ویب ایپس۔", descriptionEn: "Mobile and web application development with requirements discovery, architecture, implementation, testing, and deployment support. Quotes reflect the actual feature set.", descriptionUr: "ضروریات، آرکیٹیکچر، تیاری، ٹیسٹنگ اور ڈیپلائمنٹ کے ساتھ موبائل اور ویب ایپلیکیشن ڈیولپمنٹ۔ قیمت اصل فیچرز کے مطابق ہوتی ہے۔", deliveryEn: "Milestone based", deliveryUr: "مراحل کے مطابق", fulfillmentType: "digital", featured: true },
  { slug: "windows-installation", category: "support", icon: "monitor", titleEn: "Windows Installation", titleUr: "ونڈوز انسٹالیشن", shortEn: "Windows 10/11 installation by remote session or scheduled visit.", shortUr: "ریموٹ سیشن یا طے شدہ وزٹ کے ذریعے ونڈوز 10/11 انسٹالیشن۔", descriptionEn: "A booking-based Windows 10/11 installation service with driver setup and essential updates. Choose remote help or request an on-site visit where available. No instant checkout is taken before schedule confirmation.", descriptionUr: "ڈرائیور سیٹ اپ اور ضروری اپ ڈیٹس کے ساتھ ونڈوز 10/11 کی بکنگ پر مبنی سروس۔ ریموٹ مدد یا دستیاب علاقوں میں موقع پر وزٹ منتخب کریں۔ شیڈول کی تصدیق سے پہلے فوری ادائیگی نہیں لی جاتی۔", deliveryEn: "Scheduled appointment", deliveryUr: "طے شدہ وقت", fulfillmentType: "booking", featured: true },
  { slug: "pc-games", category: "digital", icon: "gamepad", titleEn: "PC Games", titleUr: "پی سی گیمز", shortEn: "Legitimate digital PC game sourcing and delivery support.", shortUr: "قانونی ڈیجیٹل پی سی گیمز کی فراہمی اور معاونت۔", descriptionEn: "Request a title and platform. Availability, region compatibility, license source, and exact price are confirmed before you pay. Pirated or unauthorized copies are not sold.", descriptionUr: "گیم اور پلیٹ فارم بتائیں۔ ادائیگی سے پہلے دستیابی، ریجن، لائسنس سورس اور درست قیمت کی تصدیق کی جاتی ہے۔ غیر قانونی کاپیاں فروخت نہیں کی جاتیں۔", deliveryEn: "After availability check", deliveryUr: "دستیابی کی جانچ کے بعد", fulfillmentType: "digital", featured: false },
  { slug: "book-cover-art", category: "creative", icon: "book", titleEn: "Book Cover Art", titleUr: "کتاب کا سرورق", shortEn: "Original covers designed for your genre and publishing format.", shortUr: "آپ کی صنف اور اشاعتی فارمیٹ کے لیے اصل سرورق۔", descriptionEn: "Custom cover concepts for print and digital publishing, prepared to your platform specifications. The quote depends on illustration, image licensing, formats, and revision scope.", descriptionUr: "پرنٹ اور ڈیجیٹل اشاعت کے لیے پلیٹ فارم کی ضروریات کے مطابق کسٹم سرورق۔ قیمت خاکہ، تصاویر کے لائسنس، فارمیٹس اور ترامیم پر منحصر ہے۔", deliveryEn: "Based on concept", deliveryUr: "تصور کے مطابق", fulfillmentType: "digital", featured: false },
  { slug: "script-writing", category: "writing", icon: "clapperboard", titleEn: "Script Writing", titleUr: "اسکرپٹ رائٹنگ", shortEn: "Structured scripts shaped for your audience, voice, and format.", shortUr: "آپ کے سامعین، انداز اور فارمیٹ کے مطابق منظم اسکرپٹس۔", descriptionEn: "Original scripts for videos, presentations, ads, and explainers. Research depth, duration, tone, and revision needs are agreed before quoting.", descriptionUr: "ویڈیوز، پریزنٹیشنز، اشتہارات اور وضاحتی مواد کے لیے اصل اسکرپٹس۔ قیمت سے پہلے تحقیق، دورانیہ، انداز اور ترامیم طے کی جاتی ہیں۔", deliveryEn: "Based on word count", deliveryUr: "الفاظ کی تعداد کے مطابق", fulfillmentType: "digital", featured: false },
  { slug: "assignment-writing", category: "writing", icon: "filetext", titleEn: "Assignment Support", titleUr: "اسائنمنٹ معاونت", shortEn: "Ethical research, editing, tutoring, and formatting support.", shortUr: "اخلاقی تحقیق، تدوین، رہنمائی اور فارمیٹنگ کی معاونت۔", descriptionEn: "Academic support focused on tutoring, research guidance, proofreading, citations, and formatting. Work intended for dishonest submission or academic misconduct is not provided.", descriptionUr: "تعلیمی معاونت میں رہنمائی، تحقیق، پروف ریڈنگ، حوالہ جات اور فارمیٹنگ شامل ہیں۔ دھوکہ دہی یا تعلیمی بددیانتی کے لیے کام فراہم نہیں کیا جاتا۔", deliveryEn: "Before your deadline", deliveryUr: "آپ کی آخری تاریخ سے پہلے", fulfillmentType: "digital", featured: false },
  { slug: "other-services", category: "custom", icon: "sparkles", titleEn: "Other Services", titleUr: "دیگر خدمات", shortEn: "Have a different tech or creative requirement? Send a clear brief.", shortUr: "کوئی مختلف ٹیک یا تخلیقی ضرورت ہے؟ اپنی تفصیل بھیجیں۔", descriptionEn: "Use the custom request flow for work not listed here. Share the goal, deadline, budget range, and references; you will receive an honest feasibility response and quote.", descriptionUr: "غیر درج شدہ کام کے لیے کسٹم درخواست بھیجیں۔ مقصد، آخری تاریخ، بجٹ اور حوالہ جات فراہم کریں؛ آپ کو حقیقت پسندانہ جواب اور قیمت ملے گی۔", deliveryEn: "Confirmed after review", deliveryUr: "جائزے کے بعد تصدیق", fulfillmentType: "custom", featured: false },
] as const;

export async function ensureCatalog() {
  await db.insert(services).values(catalog.map((item) => ({ ...item, pricePkr: null }))).onConflictDoNothing({ target: services.slug });
}

export async function getServices(includeInactive = false) {
  await ensureCatalog();
  return db.select().from(services).where(includeInactive ? undefined : eq(services.active, true)).orderBy(asc(services.createdAt));
}
