"use client";

import { BarChart3, ChevronDown, Download, FileUp, Inbox, LoaderCircle, MessageSquare, Package, Save, Send, Settings2, Users } from "lucide-react";
import { useState, type FormEvent } from "react";
import type { Service } from "@/db/schema";
import type { DashboardOrder } from "@/lib/types";
import { formatDate, formatPkr } from "@/lib/utils";
import { StatusPill } from "./status-pill";

type Contact = { id: string; name: string; email: string; phone: string | null; subject: string; message: string; status: string; createdAt: Date };
type Tab = "orders" | "services" | "enquiries";

export function AdminView({ name, orders, services, contacts, customerCount, paidRevenue }: { name: string; orders: DashboardOrder[]; services: Service[]; contacts: Contact[]; customerCount: number; paidRevenue: number }) {
  const [tab, setTab] = useState<Tab>("orders");
  return <><section className="admin-hero"><div className="shell admin-hero-inner"><div><p className="eyebrow">Owner dashboard</p><h1>Good work starts with clarity, {name}.</h1></div><span>Admin access</span></div></section><section className="section-tight"><div className="shell"><div className="admin-stats"><Stat icon={<BarChart3/>} label="Confirmed revenue" value={formatPkr(paidRevenue)}/><Stat icon={<Package/>} label="Active orders" value={String(orders.filter((o) => !["delivered", "cancelled"].includes(o.status)).length)}/><Stat icon={<Users/>} label="Customers" value={String(customerCount)}/><Stat icon={<Inbox/>} label="New enquiries" value={String(contacts.filter((c) => c.status === "new").length)}/></div><div className="admin-tabs"><button className={tab === "orders" ? "active" : ""} onClick={() => setTab("orders")}><Package/>Orders</button><button className={tab === "services" ? "active" : ""} onClick={() => setTab("services")}><Settings2/>Services & pricing</button><button className={tab === "enquiries" ? "active" : ""} onClick={() => setTab("enquiries")}><Inbox/>Enquiries</button></div>{tab === "orders" && <div className="admin-order-list">{orders.length ? orders.map((order) => <AdminOrder key={order.id} order={order}/>) : <div className="empty-panel">No orders received yet.</div>}</div>}{tab === "services" && <div className="admin-service-grid">{services.map((service) => <ServiceEditor key={service.id} service={service}/>)}</div>}{tab === "enquiries" && <div className="enquiry-list">{contacts.length ? contacts.map((contact) => <article key={contact.id}><header><div><b>{contact.subject}</b><span>{contact.name} · <a href={`mailto:${contact.email}`}>{contact.email}</a>{contact.phone ? ` · ${contact.phone}` : ""}</span></div><small>{formatDate(contact.createdAt)}</small></header><p>{contact.message}</p></article>) : <div className="empty-panel">No enquiries yet.</div>}</div>}</div></section></>;
}
function Stat({ icon, label, value }: { icon: React.ReactNode; label: string; value: string }) { return <div className="admin-stat"><span>{icon}</span><div><small>{label}</small><b>{value}</b></div></div>; }
function AdminOrder({ order }: { order: DashboardOrder }) {
  const [open, setOpen] = useState(false); const [busy, setBusy] = useState(""); const [notice, setNotice] = useState("");
  async function update(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy("update"); const data = Object.fromEntries(new FormData(event.currentTarget)); const response = await fetch(`/api/admin/orders/${order.id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify(data) }); const result = await response.json(); setNotice(response.ok ? "Order updated and customer notified." : result.error); setBusy(""); if (response.ok) setTimeout(() => window.location.reload(), 700); }
  async function upload(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy("upload"); const response = await fetch(`/api/orders/${order.id}/files`, { method: "POST", body: new FormData(event.currentTarget) }); const result = await response.json(); setNotice(response.ok ? "Deliverable uploaded and customer notified." : result.error); setBusy(""); }
  async function message(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy("message"); const response = await fetch(`/api/orders/${order.id}/messages`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ body: new FormData(event.currentTarget).get("body") }) }); setBusy(""); if (response.ok) window.location.reload(); else setNotice("Message could not be sent."); }
  return <article className="admin-order"><button className="admin-order-head" onClick={() => setOpen(!open)}><div><b>{order.orderNumber}</b><span>{order.customerName} · {order.customerEmail}</span></div><div><StatusPill status={order.status}/><b>{formatPkr(order.totalPkr)}</b><ChevronDown className={open ? "rotate" : ""}/></div></button>{open && <div className="admin-order-body"><div className="admin-order-context"><div><small>Services</small><b>{order.items.map((i) => i.title).join(", ")}</b></div><div><small>Placed</small><b>{formatDate(order.createdAt)}</b></div><div><small>Brief</small><p>{order.notes}</p></div></div><form className="admin-update-form" onSubmit={update}><div className="field"><label>Order status</label><select name="status" defaultValue={order.status}><option value="pending">Pending</option><option value="in_progress">In progress</option><option value="delivered">Delivered</option><option value="cancelled">Cancelled</option></select></div><div className="field"><label>Payment status</label><select name="paymentStatus" defaultValue={order.paymentStatus}><option value="unpaid">Unpaid</option><option value="payment_pending">Payment pending</option><option value="verification_pending">Verification pending</option><option value="paid">Paid</option><option value="failed">Failed</option><option value="refunded">Refunded</option></select></div><div className="field full"><label>Private admin notes</label><textarea name="adminNotes" placeholder="Internal notes only"/></div><button className="button button-small" disabled={Boolean(busy)}>{busy === "update" ? <LoaderCircle className="spin"/> : <><Save size={15}/>Save & notify</>}</button></form><section className="workspace-section"><h4><FileUp/> Deliverables</h4><div className="file-list">{order.files.map((file) => <a key={file.id} href={`/api/files/${file.id}`}><span><Download/></span><div><b>{file.originalName}</b><small>{file.kind}</small></div></a>)}</div><form className="upload-form" onSubmit={upload}><input type="hidden" name="kind" value="deliverable"/><input type="file" name="file" required/><button className="button button-small" disabled={Boolean(busy)}><FileUp/>Upload deliverable</button></form></section><section className="workspace-section"><h4><MessageSquare/> Client conversation</h4><div className="chat-list">{order.messages.map((message) => <div className="theirs" key={message.id}><b>{message.senderName}</b><p>{message.body}</p><small>{formatDate(message.createdAt)}</small></div>)}</div><form className="message-form" onSubmit={message}><input name="body" required maxLength={3000} placeholder="Reply to client…"/><button disabled={Boolean(busy)}><Send/></button></form></section>{notice && <div className="form-success">{notice}</div>}</div>}</article>;
}
function ServiceEditor({ service }: { service: Service }) { const [busy, setBusy] = useState(false); const [notice, setNotice] = useState(""); async function save(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); const form = event.currentTarget; const values = Object.fromEntries(new FormData(form)); const response = await fetch(`/api/admin/services/${service.id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...values, active: values.active === "on", featured: values.featured === "on" }) }); const result = await response.json(); setNotice(response.ok ? "Service saved." : result.error); setBusy(false); } return <form className="form-card service-editor" onSubmit={save}><header><div><small>{service.category}</small><h3>{service.titleEn}</h3></div><StatusPill status={service.active ? "active" : "inactive"}/></header><div className="form-grid"><div className="field"><label>Price in PKR (blank = quote)</label><input name="pricePkr" type="number" min="0" step="1" defaultValue={service.pricePkr ?? ""}/></div><div className="field"><label>Price label</label><input name="priceLabel" defaultValue={service.priceLabel ?? "Starting from"}/></div><div className="field"><label>Delivery — English</label><input name="deliveryEn" defaultValue={service.deliveryEn}/></div><div className="field"><label>Delivery — Urdu</label><input name="deliveryUr" defaultValue={service.deliveryUr}/></div><div className="field full"><label>Genuine gallery HTTPS URLs (comma or new line)</label><textarea name="gallery" defaultValue={service.gallery.join("\n")}/></div></div><div className="toggle-row"><label><input type="checkbox" name="active" defaultChecked={service.active}/>Active</label><label><input type="checkbox" name="featured" defaultChecked={service.featured}/>Featured</label></div>{notice && <div className="form-success">{notice}</div>}<button className="button button-small" disabled={busy}>{busy ? <LoaderCircle className="spin"/> : <Save/>}Save service</button></form>; }
